version: '3.8'

services:
  proxy-setup:
    build:
      context: ./proxy-setup
      dockerfile: Dockerfile
    container_name: proxy-setup
    hostname: proxy-setup
    command: >
      sh -c '
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout nginx.key -out nginx.crt -subj "/C=US/ST=California/L=San Francisco/O=MyOrg/OU=MyUnit/CN=localhost" -reqexts SAN -extensions SAN -config <(echo "[req]"; echo "distinguished_name=req"; echo "[SAN]"; echo "subjectAltName=DNS:localhost,DNS:proxy,DNS:trino-coordinator,DNS:playground") -addext "basicConstraints=CA:TRUE";
        echo "checking for proxy certs...";
        until curl -s -o /dev/null -w '%{http_code}' --cacert /etc/nginx/certs/nginx.crt https://proxy/v1/status | grep '200'; do echo "check failed!" && sleep 1; done;
        echo "all done!";
      '
    volumes:
      - proxy-certs:/etc/nginx/certs
    healthcheck:
      test: ['CMD-SHELL', '[ -f /etc/nginx/certs/nginx.crt ] && [ -f /etc/nginx/certs/nginx.key ]']
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - trino-internal

  proxy:
    image: nginx
    ports:
      - '443:443'
    volumes:
      - ${PWD}/proxy/nginx.conf:/etc/nginx/nginx.conf
      - proxy-certs:/etc/nginx/certs
    depends_on:
      proxy-setup:
        condition: service_healthy
      trino-coordinator:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s -o /dev/null -w '%{http_code}' --cacert /etc/nginx/certs/nginx.crt https://localhost/v1/status | grep '200'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - trino-internal
      - www

  trino-coordinator:
    image: trinodb/trino:433
    container_name: trino-coordinator
    hostname: trino-coordinator
    ports:
      - '8888:8080'
    env_file:
      - ${PWD}/docker.env
    volumes:
      - ${PWD}/coordinator/config.properties:/etc/trino/config.properties
      - ${PWD}/coordinator/password-authenticator.properties:/etc/trino/password-authenticator.properties
      - ${PWD}/extra-config:/etc/extra/trino-config
    networks:
      - trino-internal

  trino-worker:
    image: trinodb/trino:433
    depends_on:
      trino-coordinator:
        condition: service_healthy
    deploy:
      replicas: 1
    env_file:
      - ${PWD}/docker.env
    volumes:
      - ${PWD}/worker/config.properties:/etc/trino/config.properties
    networks:
      - trino-internal

  playground:
    build:
      context: ./playground
      dockerfile: Dockerfile
    container_name: playground
    hostname: playground
    command: /usr/local/bin/docker-entrypoint.sh
    depends_on:
      proxy:
        condition: service_healthy
    networks:
      - www
    volumes:
      - proxy-certs:/usr/local/share/proxy/certs

volumes:
  proxy-certs:

networks:
  trino-internal:
  www:
